[package]
name = "rustysnake"
version = "0.1.0"
authors = ["Paul Praet"]


[dependencies]
mio = "0.6.12"
evdev-rs = { git = "https://github.com/huntaub/evdev-rs" }
nix = "0.7.0"
libc = "0.2.36"
rgb = "0.8.6"
rand = "0.4"

[dependencies.unicorn_hat_hd]
version = "0.2.1"
default-features = false

#Use line below when cross-compiling for Raspberry Pi
features = ["hardware"]

#Use line below to build for host
#features = ["fake-hardware"]
