[target.armv7-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install --assume-yes python3 doxygen graphviz"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["apt-get update && apt-get install --assume-yes python3 doxygen graphviz"]
