#!/bin/bash

function install_systemd() {
    touch /etc/default/rustysnake
    /bin/systemctl enable rustysnake
    /bin/systemctl restart rustysnake
}

install_systemd >> "/tmp/rustysnake.log" 2>&1

exit 0
